#!/usr/bin/env python3
"""Build theme.css and tokens.json from tokens.yaml."""
import json
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML is required: pip install pyyaml")

PKG_DIR = Path(__file__).resolve().parent / "src" / "text_engine_webui_theme_template"
TOKENS_YAML = PKG_DIR / "tokens.yaml"
TOKENS_JSON = PKG_DIR / "tokens.json"
THEME_CSS = PKG_DIR / "theme.css"

# The theme ID must match the entry_points name in setup.py
THEME_ID = "my-custom-theme"


def main() -> None:
    data = yaml.safe_load(TOKENS_YAML.read_text())

    # Write tokens.json
    TOKENS_JSON.write_text(json.dumps(data, indent=2) + "\n")
    print(f"Wrote {TOKENS_JSON}")

    # Build CSS
    lines = [
        "/* Generated by build_theme.py — do not edit directly. */",
        f'html[data-theme="{THEME_ID}"] {{',
    ]
    for key, value in data.items():
        # Skip non-CSS entries
        lines.append(f"  --{key}: {value};")
    lines.append("}")

    THEME_CSS.write_text("\n".join(lines) + "\n")
    print(f"Wrote {THEME_CSS}")


if __name__ == "__main__":
    main()
